// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qulix_Test_Task.Data;

namespace Qulix_Test_Task.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20200708155126_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Qulix_Test_Task.Data.Models.Company", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("company_size");

                    b.Property<string>("incorporation_form");

                    b.Property<string>("сompany_name");

                    b.HasKey("id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Qulix_Test_Task.Data.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("companyID");

                    b.Property<string>("employment_date");

                    b.Property<string>("lastname");

                    b.Property<string>("name");

                    b.Property<string>("position");

                    b.Property<string>("surname");

                    b.HasKey("id");

                    b.HasIndex("companyID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Qulix_Test_Task.Data.Models.Employee", b =>
                {
                    b.HasOne("Qulix_Test_Task.Data.Models.Company", "Company")
                        .WithMany("employees")
                        .HasForeignKey("companyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
